#!/usr/bin/env bash
# displays listening port

echo "Active Internet connections (only servers)"
echo "Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name"
sudo netstat -tulnp | grep LISTEN

echo ""
echo "Active UNIX domain sockets (only servers)"
echo "Proto RefCnt Flags       Type       State         I-Node   PID/Program name    Path"
sudo netstat -lxnp | grep LISTEN

