#!/usr/bin/env bash
# accepts a string of arguemnets and displays a certain message if no arguments were  passed and pings  the IP 5 times

read string
if [ $# -eq 0 ];
then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	ping $string
fi
