#!/usr/bin/env bash
# this script loops from 1 to 10 and prints a certain phrase
num=1
while [ $num -le 10 ]
do
	if [ $num == 4 ]
	then
		echo "bad luck"
	elif [ $num == 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	num=$(( num+1 ))
done
