#!/usr/bin/env bash
# bash script that displays numbers from 1 to 20 but with some certain texts injected
num=1
while [ $num -le 20 ]
do
	case $num in
		4)
			echo "$num"
			echo "bad luck from China"
			;;
		9)
			echo "$num"
			echo "bad luck from Japan"
			;;
		17)
			echo "$num"
			echo "bad luck from Italy"
			;;
		*)
			echo "$num"
			;;
	esac
	num=$(( num+1 ))
done
