#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes
num=0
min=1
while [ $num -le 12 ]
do
	echo "Hour: $num"
	if [ $num != 12 ]
	then
		min=1
		while [ $min -le 59 ]
		do
			echo "$min"
			min=$(( min+1 ))
		done
	fi
	num=$(( num+1 ))
done

